version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hi:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    machine:
      image: ubuntu-2004:202010-01
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Update git"
          command: "git config --global http.sslverify false && git submodule update --init --recursive"
      - run:
          name: "Install"
          command: "./install.sh && cat build/bin/asteroid"      
      - run:
          name: "Coucou"
          command: "ls build/bin/asteroid"
      - store_artifacts:
          path: build/bin/asteroid
          destination: artifact-file
  



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hi

